
## Below you have a code that raises an exception , using what you learned do the following:

def additoin(x, y):

    try:
        x = 10
        y = 20
        print("Addition:", x + b)
    except NameError:
        print ("a variable used in addition operation is undefined")
    else:
        print("operation is successful")
    


additoin(10, 20)
